language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip setuptools
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest
after_success:
  - codecov
