language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip setuptools
install:
  - pip install -r requirements-dev.txt
script: pytest --cov
after_success:
  - codecov
