[tool.black]
line-length = 120
target-version = ["py39"]
include = ".py$"

[tool.coverage.run]
source = ["app/"]

[tool.isort]
profile = "black"
line_length = 120
lines_after_imports = 2

[tool.pytest.ini_options]
testpaths = ["app/tests"]
addopts = "--cov -r a -v"
