"""

Revision ID: 258f4b997ae2
Revises: d45b762c6d69
Create Date: 2021-11-17 20:54:35.421541

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "258f4b997ae2"
down_revision = "d45b762c6d69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("rating", sa.Integer(), nullable=False))
    op.drop_index("ix_participant_absent_rounds", table_name="participant")
    op.drop_index("ix_participant_bye_rounds", table_name="participant")
    op.create_index(
        op.f("ix_participant_rating"), "participant", ["rating"], unique=False
    )
    op.drop_column("participant", "absent_rounds")
    op.drop_column("participant", "bye_rounds")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("bye_rounds", sa.INTEGER(), nullable=False))
    op.add_column(
        "participant", sa.Column("absent_rounds", sa.INTEGER(), nullable=False)
    )
    op.drop_index(op.f("ix_participant_rating"), table_name="participant")
    op.create_index(
        "ix_participant_bye_rounds", "participant", ["bye_rounds"], unique=False
    )
    op.create_index(
        "ix_participant_absent_rounds", "participant", ["absent_rounds"], unique=False
    )
    op.drop_column("participant", "rating")
    # ### end Alembic commands ###
