"""

Revision ID: d45b762c6d69
Revises: ce349a7ca482
Create Date: 2021-11-17 19:01:10.196937

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d45b762c6d69"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
    )
    op.create_index(op.f("ix_player_country"), "player", ["country"], unique=False)
    op.create_index(
        op.f("ix_player_first_name"), "player", ["first_name"], unique=False
    )
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_index(op.f("ix_player_last_name"), "player", ["last_name"], unique=False)
    op.create_index(op.f("ix_player_rating"), "player", ["rating"], unique=False)
    op.create_table(
        "tournament",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("number_of_rounds", sa.Integer(), nullable=False),
        sa.Column("mm_floor", sa.Integer(), nullable=False),
        sa.Column("mm_bar", sa.Integer(), nullable=False),
        sa.Column("mm_dense", sa.Boolean(), nullable=False),
        sa.Column("handicap_bar", sa.Integer(), nullable=False),
        sa.Column("handicap_max", sa.Integer(), nullable=False),
        sa.Column("handicap_correction", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
    )
    op.create_index(
        op.f("ix_tournament_handicap_bar"),
        "tournament",
        ["handicap_bar"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_handicap_correction"),
        "tournament",
        ["handicap_correction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tournament_handicap_max"),
        "tournament",
        ["handicap_max"],
        unique=False,
    )
    op.create_index(op.f("ix_tournament_id"), "tournament", ["id"], unique=False)
    op.create_index(
        op.f("ix_tournament_mm_bar"), "tournament", ["mm_bar"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_mm_dense"), "tournament", ["mm_dense"], unique=False
    )
    op.create_index(
        op.f("ix_tournament_mm_floor"), "tournament", ["mm_floor"], unique=False
    )
    op.create_index(op.f("ix_tournament_name"), "tournament", ["name"], unique=False)
    op.create_index(
        op.f("ix_tournament_number_of_rounds"),
        "tournament",
        ["number_of_rounds"],
        unique=False,
    )
    op.create_table(
        "participant",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("start_mms", sa.Integer(), nullable=False),
        sa.Column("absent_rounds", sa.Integer(), nullable=False),
        sa.Column("bye_rounds", sa.Integer(), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
    )
    op.create_index(
        op.f("ix_participant_absent_rounds"),
        "participant",
        ["absent_rounds"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_bye_rounds"),
        "participant",
        ["bye_rounds"],
        unique=False,
    )
    op.create_index(op.f("ix_participant_id"), "participant", ["id"], unique=False)
    op.create_index(
        op.f("ix_participant_is_final"),
        "participant",
        ["is_final"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_player_id"),
        "participant",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_start_mms"),
        "participant",
        ["start_mms"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_tournament_id"),
        "participant",
        ["tournament_id"],
        unique=False,
    )
    op.create_table(
        "game",
        sa.Column("white_id", sa.Integer(), nullable=False),
        sa.Column("black_id", sa.Integer(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("handicap", sa.Integer(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("by_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["black_id"],
            ["participant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["white_id"],
            ["participant.id"],
        ),
    )
    op.create_index(op.f("ix_game_black_id"), "game", ["black_id"], unique=False)
    op.create_index(op.f("ix_game_by_default"), "game", ["by_default"], unique=False)
    op.create_index(op.f("ix_game_handicap"), "game", ["handicap"], unique=False)
    op.create_index(op.f("ix_game_id"), "game", ["id"], unique=False)
    op.create_index(op.f("ix_game_result"), "game", ["result"], unique=False)
    op.create_index(
        op.f("ix_game_round_number"), "game", ["round_number"], unique=False
    )
    op.create_index(op.f("ix_game_white_id"), "game", ["white_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_white_id"), table_name="game")
    op.drop_index(op.f("ix_game_round_number"), table_name="game")
    op.drop_index(op.f("ix_game_result"), table_name="game")
    op.drop_index(op.f("ix_game_id"), table_name="game")
    op.drop_index(op.f("ix_game_handicap"), table_name="game")
    op.drop_index(op.f("ix_game_by_default"), table_name="game")
    op.drop_index(op.f("ix_game_black_id"), table_name="game")
    op.drop_table("game")
    op.drop_index(op.f("ix_participant_tournament_id"), table_name="participant")
    op.drop_index(op.f("ix_participant_start_mms"), table_name="participant")
    op.drop_index(op.f("ix_participant_player_id"), table_name="participant")
    op.drop_index(op.f("ix_participant_is_final"), table_name="participant")
    op.drop_index(op.f("ix_participant_id"), table_name="participant")
    op.drop_index(op.f("ix_participant_bye_rounds"), table_name="participant")
    op.drop_index(op.f("ix_participant_absent_rounds"), table_name="participant")
    op.drop_table("participant")
    op.drop_index(op.f("ix_tournament_number_of_rounds"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_name"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_mm_floor"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_mm_dense"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_mm_bar"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_id"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_handicap_max"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_handicap_correction"), table_name="tournament")
    op.drop_index(op.f("ix_tournament_handicap_bar"), table_name="tournament")
    op.drop_table("tournament")
    op.drop_index(op.f("ix_player_rating"), table_name="player")
    op.drop_index(op.f("ix_player_last_name"), table_name="player")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_index(op.f("ix_player_first_name"), table_name="player")
    op.drop_index(op.f("ix_player_country"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
