"""

Revision ID: d4e20e87a0af
Revises: 258f4b997ae2
Create Date: 2021-11-25 19:16:01.742523

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d4e20e87a0af"
down_revision = "258f4b997ae2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tournament", sa.Column("status", sa.String(), nullable=True))

    op.create_table(
        "scoring",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("points_x2", sa.Integer(), nullable=True),
        sa.Column("points_x2_virtual", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["participant_id"], ["participant.id"]),
    )

    op.create_index(op.f("ix_scoring_id"), "scoring", ["id"], unique=False)
    op.create_index(
        op.f("ix_scoring_participant_id"), "scoring", ["participant_id"], unique=False
    )
    op.create_index(
        op.f("ix_scoring_points_x2"), "scoring", ["points_x2"], unique=False
    )
    op.create_index(
        op.f("ix_scoring_points_x2_virtual"),
        "scoring",
        ["points_x2_virtual"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scoring_round_number"), "scoring", ["round_number"], unique=False
    )
    op.create_index(op.f("ix_scoring_status"), "scoring", ["status"], unique=False)
    op.create_index(
        op.f("ix_tournament_status"), "tournament", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tournament_status"), table_name="tournament")
    op.drop_column("tournament", "status")
    op.drop_index(op.f("ix_scoring_status"), table_name="scoring")
    op.drop_index(op.f("ix_scoring_round_number"), table_name="scoring")
    op.drop_index(op.f("ix_scoring_points_x2_virtual"), table_name="scoring")
    op.drop_index(op.f("ix_scoring_points_x2"), table_name="scoring")
    op.drop_index(op.f("ix_scoring_participant_id"), table_name="scoring")
    op.drop_index(op.f("ix_scoring_id"), table_name="scoring")
    op.drop_table("scoring")
    # ### end Alembic commands ###
